import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import AnimatedBackground from '@/components/AnimatedBackground';
import { getQuestionSets } from '@/lib/teacherStorage';
import { playClickSound } from '@/lib/sounds';
import { ArrowLeft, BookOpen, Sparkles } from 'lucide-react';

const SelectQuestionSet: React.FC = () => {
  const navigate = useNavigate();
  const questionSets = getQuestionSets();

  const handleBack = () => {
    playClickSound();
    navigate('/');
  };

  const handleSelectSet = (setId: string) => {
    playClickSound();
    navigate(`/play/${setId}`);
  };

  const handleAutoGenerated = () => {
    playClickSound();
    navigate('/levels');
  };

  return (
    <main className="relative min-h-screen overflow-hidden">
      <AnimatedBackground />

      <div className="relative z-10 min-h-screen p-4 md:p-8">
        <div className="max-w-4xl mx-auto">
          <Button
            variant="outline"
            onClick={handleBack}
            className="mb-8 font-fredoka"
          >
            <ArrowLeft className="w-5 h-5 mr-2" />
            Back
          </Button>

          <div className="text-center mb-10">
            <h1 className="text-3xl md:text-5xl font-baloo font-bold text-foreground text-shadow-fun mb-4">
              📚 Choose Your Adventure
            </h1>
            <p className="text-lg font-fredoka text-foreground/80">
              Select a question set to play
            </p>
          </div>

          <div className="grid gap-4">
            {/* Auto-generated option */}
            <button
              onClick={handleAutoGenerated}
              className="bg-gradient-to-r from-primary/90 to-accent/90 backdrop-blur-sm rounded-2xl p-6 shadow-xl text-left hover:scale-[1.02] transition-transform"
            >
              <div className="flex items-center gap-4">
                <div className="w-14 h-14 rounded-xl bg-background/20 flex items-center justify-center">
                  <Sparkles className="w-7 h-7 text-primary-foreground" />
                </div>
                <div>
                  <h3 className="text-xl font-baloo font-bold text-primary-foreground">
                    Auto-Generated Islands
                  </h3>
                  <p className="text-primary-foreground/80 font-fredoka">
                    100 levels with progressively harder math problems
                  </p>
                </div>
              </div>
            </button>

            {/* Teacher-created sets */}
            {questionSets.map((set) => (
              <button
                key={set.id}
                onClick={() => handleSelectSet(set.id)}
                className="bg-card/90 backdrop-blur-sm rounded-2xl p-6 shadow-xl text-left hover:scale-[1.02] transition-transform"
              >
                <div className="flex items-center gap-4">
                  <div className="w-14 h-14 rounded-xl bg-primary/20 flex items-center justify-center">
                    <BookOpen className="w-7 h-7 text-primary" />
                  </div>
                  <div>
                    <h3 className="text-xl font-baloo font-bold text-foreground">
                      {set.name}
                    </h3>
                    <p className="text-muted-foreground font-fredoka">
                      {set.questions.length} question{set.questions.length !== 1 ? 's' : ''} • Teacher Created
                    </p>
                  </div>
                </div>
              </button>
            ))}

            {questionSets.length === 0 && (
              <div className="bg-card/60 backdrop-blur-sm rounded-2xl p-8 text-center">
                <p className="text-muted-foreground font-fredoka">
                  No teacher-created question sets yet.
                  <br />
                  Ask your teacher to create some!
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
};

export default SelectQuestionSet;
